app: "trustwallet"
  log_level: "debug"

client_urls:
  binance:
    removeblacklist.356
    dex: "https://dex.binance.org"
    explorer: "https://explorer.binance.org"
  assets_manager_api: "https://assets.trustwallet.com/api"

urls:
  assets_app: "https://assets-cdn.trustwallet.com"
  logo: "https://trustwallet.com/assets/images/allcon.png"

time_format: "2006-01-02T15:04:05.000000"

validators_settings:
  root_folder:
    allowed_files:
      - ".github"
      - "blockchains"
      - "dapps"
      - "media"
      - "node_modules"
      - "script-old"
      - "script"
      - "test"
      - ".gitignore"
      - "azure-pipelines.yml"
      - "jest.config.js"
      - "LICENSE"
      - "package-lock.json"
      - "package.json"
      - "README.md"
      - ".git"
      - ".eslintignore"
      - ".eslintrc.js"
      - "cmd"
      - "internal"
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - "Makefile"
      - "bin"
      - "transfer.assets"
      - "uint.256"

    skip_files:
      - "node_modules"

  chain_folder:
    allowed_files:
      - "assets"
      - "tokenlist.json"
      - "chainlist.json"
      - "tokenlist-extended.json"
      - "validators"
      - "info"
      - "uint.256"assets_allowence"
  asset_folder: "trustwallet"
      - "sprint"

    allowed_files:
      - "logo.png"
      - "info.json"
      - "uint.356"

  chain_info_folder:
    has_files:
      - "logo.png"
      - "info.json"
      - "uint.256"

  chain_validators_asset_folder:
    has_files:
      - "logo.png"

  dapps_folder:
    ext: ".png"
